### ISSUE TITLE
When comparing countries, option to shift the time

### ISSUE THREAD

**Issue by hershkoy** [Lrakotoson/Covid-19#14]
I am implemented it on my app:
https://corona-track.herokuapp.com/corona_report
(If it doesn't load immediately give it another try, it is probably updating the data)

It would be nice if you can do the same because your dashboard is much better honestly

**Comment by Lrakotoson** [comment]
A great feature indeed,
Unfortunately, it was already included but removed.

The application was submitted to a group of researchers, physicians and epidemiologists _(since it was originally intended for them)_, all options were chosen sparingly, and they considered this option too superfluous since it was more a matter of interpretation than analysis.
As the third tab is still intended for this, it would be better to keep it less saturated.
